# Site settings
title: Alex Luu
email: luualex23@gmail.com
description: > # keep this and put description below
  Game Programmer 
url: "https://alexluu597.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/alex-luu-71343725a"
github_username: alexluu597
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
